# Generated by Django 5.1.2 on 2024-10-21 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customusermodel_type'),
        ('job', '0004_alter_applymodel_status_alter_jobmodel_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.company'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='type',
            field=models.CharField(choices=[('Job Seeker', 'Job Seeker'), ('Employee', 'Employee'), ('Viewer', 'Viewer')], default='Viewer', max_length=40),
        ),
    ]
