# Generated by Django 5.1.2 on 2024-10-29 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customusermodel_type'),
        ('job', '0006_alter_applymodel_status_alter_jobmodel_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.company'),
        ),
    ]
