# Generated by Django 5.1.2 on 2024-11-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customusermodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='type',
            field=models.CharField(choices=[('Employee', 'Employee'), ('admin', 'Admin'), ('Job Seeker', 'Job Seeker'), ('Viewer', 'Viewer')], default='Viewer', max_length=40),
        ),
    ]
