# Generated by Django 5.1.2 on 2024-11-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customusermodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('Viewer', 'Viewer'), ('Employee', 'Employee'), ('Job Seeker', 'Job Seeker')], default='Viewer', max_length=40),
        ),
    ]
