# Generated by Django 5.1.2 on 2024-11-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customusermodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='type',
            field=models.CharField(choices=[('Viewer', 'Viewer'), ('admin', 'Admin'), ('Job Seeker', 'Job Seeker'), ('Employee', 'Employee')], default='Viewer', max_length=40),
        ),
    ]
