# Generated by Django 5.1.2 on 2024-10-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_applymodel_status_alter_jobmodel_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Accepted', 'Accepted')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_type',
            field=models.CharField(choices=[('Semi-Government', 'Semi-Government'), ('Government', 'Government'), ('Privet', 'Privet')], default='Privet', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='time',
            field=models.CharField(blank=True, choices=[('Full-Time', 'Full-Time'), ('Half-time', 'Half-time')], default='Full-Time', max_length=20, null=True),
        ),
    ]
