# Generated by Django 5.1.2 on 2024-10-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_applymodel_status_alter_jobmodel_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymodel',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_type',
            field=models.CharField(choices=[('Government', 'Government'), ('Privet', 'Privet'), ('Semi-Government', 'Semi-Government')], default='Privet', max_length=100),
        ),
    ]
