# Generated by Django 5.1.2 on 2024-10-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_applymodel_status_alter_jobmodel_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymodel',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_type',
            field=models.CharField(choices=[('Semi-Government', 'Semi-Government'), ('Government', 'Government'), ('Privet', 'Privet')], default='Privet', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='time',
            field=models.CharField(blank=True, choices=[('Half-time', 'Half-time'), ('Full-Time', 'Full-Time')], default='Full-Time', max_length=20, null=True),
        ),
    ]
