# Generated by Django 5.1.2 on 2024-10-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_applymodel_status_alter_jobmodel_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='./company'),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_type',
            field=models.CharField(choices=[('Government', 'Government'), ('Semi-Government', 'Semi-Government'), ('Privet', 'Privet')], default='Privet', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='time',
            field=models.CharField(blank=True, choices=[('Full-Time', 'Full-Time'), ('Half-time', 'Half-time')], default='Full-Time', max_length=20, null=True),
        ),
    ]
