# Generated by Django 5.1.2 on 2024-10-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_company_logo_alter_jobmodel_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymodel',
            name='resume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applymodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_type',
            field=models.CharField(choices=[('Semi-Government', 'Semi-Government'), ('Government', 'Government'), ('Privet', 'Privet')], default='Privet', max_length=100),
        ),
    ]
