# Generated by Django 5.1.2 on 2024-11-03 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_alter_applymodel_status_alter_applymodel_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymodel',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='applymodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_type',
            field=models.CharField(choices=[('Privet', 'Privet'), ('Semi-Government', 'Semi-Government'), ('Government', 'Government')], default='Privet', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='time',
            field=models.CharField(blank=True, choices=[('Full-Time', 'Full-Time'), ('Half-time', 'Half-time')], default='Full-Time', max_length=20, null=True),
        ),
    ]
