# Generated by Django 5.1.2 on 2024-11-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_alter_applymodel_status_alter_jobmodel_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymodel',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_type',
            field=models.CharField(choices=[('Privet', 'Privet'), ('Government', 'Government'), ('Semi-Government', 'Semi-Government')], default='Privet', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='time',
            field=models.CharField(blank=True, choices=[('Half-time', 'Half-time'), ('Full-Time', 'Full-Time')], default='Full-Time', max_length=20, null=True),
        ),
    ]
