# Generated by Django 5.1.2 on 2024-11-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_alter_applymodel_status_alter_jobmodel_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='job_type',
            field=models.CharField(choices=[('Government', 'Government'), ('Privet', 'Privet'), ('Semi-Government', 'Semi-Government')], default='Privet', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='time',
            field=models.CharField(blank=True, choices=[('Full-Time', 'Full-Time'), ('Half-time', 'Half-time')], default='Full-Time', max_length=20, null=True),
        ),
    ]
