# Generated by Django 5.1.2 on 2024-11-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_alter_jobmodel_job_type_alter_jobmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymodel',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_type',
            field=models.CharField(choices=[('Government', 'Government'), ('Semi-Government', 'Semi-Government'), ('Privet', 'Privet')], default='Privet', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='time',
            field=models.CharField(blank=True, choices=[('Half-time', 'Half-time'), ('Full-Time', 'Full-Time')], default='Full-Time', max_length=20, null=True),
        ),
    ]
