# Generated by Django 5.1.2 on 2024-11-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_alter_applymodel_status_alter_jobmodel_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymodel',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_type',
            field=models.CharField(choices=[('Privet', 'Privet'), ('Semi-Government', 'Semi-Government'), ('Government', 'Government')], default='Privet', max_length=100),
        ),
    ]
